[workspace]
members = ["benchmarks/bench_*", "bench-multicore"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Elena Frank <elena.frank@proton.me>"]

[workspace.dependencies]
bench-multicore = { path = "bench-multicore" }

ariel-os = { git = "https://github.com/ariel-os/ariel-os", rev = "9b4e4e0d70ac81bf78d2efcaf2d240ff0097a187", features = [
  "bench",
] }
ariel-os-boards = { git = "https://github.com/ariel-os/ariel-os", rev = "9b4e4e0d70ac81bf78d2efcaf2d240ff0097a187" }

cortex-m = { version = "0.7", default-features = false }
esp-hal = { version = "0.23.1", default-features = false, features = [
  "unstable",
] }
xtensa-lx-rt = { version = "0.18.0", default-features = false }

cfg-if = { version = "1.0.0" }
critical-section = { version = "1.1.2", default-features = false }
defmt = { version = "1.0.0" }

[workspace.lints.rust]
